---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: Lite-Bazzite-Gnome
description: Ban Bazzite GNOME sieu nhe - Duyen sach app rac cho ThinkPad

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # GO SACH DANG APP TRONG ANH CHUP
  - type: dnf
    remove:
      packages:
        # Trong thu muc "Abandoned" (Anh 2)
        - waydroid
        - lutris

        # Trong thu muc "Games" (Anh 3)
        - steam

        # Trong thu muc "He Thong" (Anh 1)
        - btrfs-assistant
        - firewalld-gui
        - malcontent-control
        - bazzite-documentation
        - bazzite-portal

  # GO CAC FLATPAK CHEN SAN TRONG HE THONG
  - type: default-flatpaks
    configurations:
      notify: true
      scope: system
    remove:
      - com.discordapp.Discord
      - net.brew_brew.BoldBrew
    install:
      - org.mozilla.firefox

  - type: signing