---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: Lite-Bazzite-Gnome
description: Ban Bazzite GNOME sieu nhe cho ThinkPad

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # CHINHS GOIC CHUAN AN TOAN DE BLUEBUILD KHONG BAO LOI
  - type: dnf
    remove:
      packages:
        - waydroid
        - lutris
        - steam
        - btrfs-assistant
        - firewalld-gui

  - type: default-flatpaks
    configurations:
      notify: true
      scope: system
    remove:
      - com.discordapp.Discord
      - net.brew_brew.BoldBrew
    install:
      - org.mozilla.firefox

  - type: signing
