---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: Lite-Bazzite-Gnome
description: Ban Bazzite GNOME sieu nhe cho ThinkPad

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # DUNG MODULE RPM-OSTREE CHUAN CUA BLUEBUILD
  - type: rpm-ostree
    remove:
      - gnome-tour
      - gnome-weather
      - gnome-maps
      - cheese

  # GO APP FLATPAK HE THONG
  - type: default-flatpaks
    configurations:
      notify: true
      scope: system
    remove:
      - com.discordapp.Discord
      - net.brew_brew.BoldBrew
    install:
      - org.mozilla.firefox

  - type: signing
